from pathlib import Path

PROJECT = <PROJECT_ID> 
LOCATION="us"
PROCESSOR_ID=<PROCESSOR_ID>
PROCESSOR_VERSION=<PROCESSOR_VERSION>
HAS_TABLES=True
FILENAME=<DOCUMENT_LOCATION>
SPLITTER="text" 
CHUNK_SIZE=1000
CHUNK_OVERLAP=100
EMBEDDINGS="google-gecko"
RETRIEVER="faiss"
LLM_MODEL="gemini"
